- hosts: kubs
  become: yes
  tasks:
   - name: disable SELinux
     command: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled
   
   - name: disable swap
     command: swapoff -a

 
   - name: install Docker
     yum:
       name: docker
       state: present
       update_cache: true

   - name: start Docker
     service:
       name: docker
       state: started
   
   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

  # - name: install kubelet
  #   yum:
  #      name: kubernetes-client.x86_64 
  #      state: present
  #      update_cache: true

  # - name: install kubeadm
  #   yum:
  #      name: kubernetes-client.x86_64
  #      state: present

   - name: install kubelet & kubeadm
     command: yum install -y kubelet kubeadm --disableexcludes=kubernetes

  # - name: install kubeadm
  #   command: yum install -y kubeadm 

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: 192.168.0.28
  become: yes
  tasks:
   - name: install kubectl
     command: yum install -y kubectl
